[theme]
base = "light"
primaryColor = "#49b156"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f2f0e6"
textColor = "#171717"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
